### ISSUE TITLE
Hi! I want to know how to solve this problem

### ISSUE THREAD

**Issue by oddmen** [pencoa/PCNN#1]
--- Logging error ---
Traceback (most recent call last):
  File "/home/xyx/anaconda3/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/xyx/anaconda3/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/xyx/anaconda3/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/home/xyx/anaconda3/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/xyx/PCNN/train.py", line 26, in <module>
    main()
  File "/home/xyx/PCNN/train.py", line 12, in main
    model.build()
  File "/home/xyx/PCNN/model/pcnn_model.py", line 312, in build
    self.log_trainable()
  File "/home/xyx/PCNN/model/pcnn_model.py", line 297, in log_trainable
    self.logger.info("Shape: ", v.shape)
Message: 'Shape: '
Arguments: ((53,),)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
Epoch 1 out of 15

**Comment by pencoa** [comment]
Thank you for your error reporting. 
That is a warning from logging module. And it has been fixed. 

There are still some bugs in this project. I find my time to fix them.
