### ISSUE TITLE
Have wrong when I run evaluate.py

### ISSUE THREAD

**Issue by JunKuang-algo** [pencoa/PCNN#3]
When I run evaluate.py, it has wrong about "AttributeError: 'Config' object has no attribute 'processing_tag'."  Could you please tell me how can I solve it?
Thank you!

The detail is shown below

`python evaluate.py
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Initializing tf session
2018-09-26 15:53:01.238774: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-09-26 15:53:02.296384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:3b:00.0
totalMemory: 22.38GiB freeMemory: 22.21GiB
2018-09-26 15:53:02.296457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-26 15:53:02.623675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-26 15:53:02.623747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-26 15:53:02.623760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-26 15:53:02.624118: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21549 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:3b:00.0, compute capability: 6.1)
Variable: pos1/_pos1_embeddings:0
Shape: (500, 5)
Variable: pos2/_pos2_embeddings:0
Shape: (500, 5)
Variable: conv/conv/kernel:0
Shape: (3, 60, 1, 230)
Variable: conv/conv/bias:0
Shape: (230,)
Variable: proj/W1:0
Shape: (690, 53)
Variable: proj/b:0
Shape: (53,)
Reloading the model in ./results/test/model.weights/early_best.ckpt...
INFO:tensorflow:Restoring parameters from ./results/test/model.weights/early_best.ckpt
Restoring parameters from ./results/test/model.weights/early_best.ckpt
Traceback (most recent call last):
  File "evaluate.py", line 69, in <module>
    main()
  File "evaluate.py", line 61, in main
    config.processing_tag, config.max_iter)
AttributeError: 'Config' object has no attribute 'processing_tag'
`

**Comment by pencoa** [comment]
You have figure out the problem by yourself, welcome to fix and pull.
